<?php if (!$this->getQuote()->isVirtual()): ?>
    <?php echo $this->helper('giftmessage/message')->getInline('onepage_checkout', $this->getQuote(), $this->getDontDisplayContainer()) ?>
<?php endif; ?>
<div id="ups-ship-additional" style="display: none">
    <input type="hidden" class="validate-ups-pickup" name="shipping_ups_pickup_id" id="pickup-id" />
    <input type="hidden" name="shipping_additional_information" id="shipping-additional" />
    <div onclick="window.PickupsSDK.onClick(); return;" class="ups-pickups ups-pickups-48"></div>
    <div class="ups-pickups-info"></div>
</div>
<script type="text/javascript">
    //<![CDATA[
    if (!window.upsShipLoaded) {
        var script = document.createElement('script');
        script.src = "<?php echo Mage::getBaseUrl('js'); ?>sr/upsship/pickup.js";
        jQuery('head').append(script);
        window.upsShipLoaded = true;
    }

    jQuery('input[name=shipping_method]').on('change', function (e) {
        if (jQuery(e.target).val() == 'upsship_pickup') {
            jQuery('#ups-ship-additional').show();
        } else {
            jQuery('#ups-ship-additional').hide();
        }
    });

    jQuery(document.body).on('pickups-before-open', function () {
        var o = {
            location: {
                city: jQuery('input[name="shipping[city]"]').val(),
                street: jQuery('input[name="shipping[street][]"]').val()
            }
        };
        var json = JSON.stringify(o);
        window.PickupsSDK.setDefaults(json);
    });

    jQuery(document.body).on('pickups-after-choosen', function (e, data) {
        var pkps_location = e.originalEvent.detail;
        console.log("pickups-after-choosen catched event", pkps_location);
        jQuery("input[name=shipping_ups_pickup_id]").val(pkps_location.iid);
        jQuery("input[name=shipping_additional_information]").val(JSON.stringify(pkps_location));
        var html = "<br /><b>" + pkps_location.title + "</b>&nbsp;(" + pkps_location.iid + ")<br />" + pkps_location.city + ", " + pkps_location.street + "<br /><small>" + pkps_location.zip + "</small>";
        jQuery("div.ups-pickups-info").css("line-height", "1em").css("font-weight", "300").css("font-size", "0.9em").html(html);
    });
    //]]>
</script>
