<div id="ups-ship-additional" class="ups-ship-additional clearfix" style="display: none">
    <input type="hidden" class="validate-ups-pickup" name="shipping_ups_pickup_id" id="pickup-id"/>
    <input type="hidden" name="shipping_additional_information" id="shipping-additional"/>
    <div onclick="window.PickupsSDK.onClick(); return;" class="ups-pickups ups-pickups-48"></div>
    <div id="ups-pickups-info" class="ups-pickups-info-2"></div>
</div>
<script type="text/javascript">
    //<![CDATA[
    if (!window.upsShipLoaded) {
        var script = document.createElement('script');
        script.src = '<?php echo Mage::helper('sr_upsship')->getPickupLocationJsUrl(); ?>';

        jQuery('head').append(script);
        window.upsShipLoaded = true;
    }

    (function ($) {
        window.UPSShip = {
            code: 'upsship_pickup',
            init: function () {
                this.checkbox = $('#s_method_upsship_pickup');
                this.block = $('#ups-ship-additional');
                this.pickInfo = $("#ups-pickups-info");
                this.picker = $('.ups-pickups-48');
                this.invalidClass = 'ups-invalid';

                var self = this;

                $('input[name=shipping_method]').on('change', $.proxy(this.shippingMethodChanged, this));

                this.bindPicker();


                if (this.isActiveMethod()) {
                    this.block.show();
                }

                // steal checkout validation function

                // in case Amasty Single Checkout is active
                if ($.isFunction(completeCheckout)) {
                    var save = completeCheckout;
                    completeCheckout = function () {
                        if (!self.isValid()) {
                            alert('<?php echo $this->__('Please choose a pickup location');?>');
                            return false;
                        }
                        return save.apply(this, arguments);
                    };
                }
                else {
                    // native shipping Class save function
                    var save = shippingMethod.save;
                    shippingMethod.save = function () {
                        if (!self.isValid()) {
                            alert('<?php echo $this->__('Please choose a pickup location');?>');
                            return false;
                        }
                        return save.apply(this, arguments);
                    };
                }

            },
            shippingMethodChanged: function (e) {
                this.block[this.isActiveMethod() ? 'show' : 'hide']();
            },
            isActiveMethod: function () {
                return this.checkbox.is(':checked');
            },
            isValid: function () {
                if (!this.isActiveMethod()) {
                    return true;
                }

                var isValid = $("input[name=shipping_ups_pickup_id]").val() != '' &&
                    $("input[name=shipping_additional_information]").val() != '';
                if (!isValid) {
                 this.block.addClass(this.invalidClass);
                }

                return isValid;
            },
            bindPicker: function () {

                var self = this;
                $('body').on('pickups-before-open', function () {
                    var city = $.trim($('input[name="shipping[city]"]').val()) != '' ? $('input[name="shipping[city]"]').val()
                        : $('input[name="billing[city]"]').val();

                    var street = $.trim($('input[name="shipping[street][]"]').val()) != '' ? $('input[name="shipping[street][]"]').val()
                        : $('input[name="billing[street][]"]').val();

                    var o = {
                        location: {
                            city: city,
                            street: street
                        }
                    };
                    var json = JSON.stringify(o);
                    window.PickupsSDK.setDefaults(json);

                }).on('pickups-after-choosen', function (e, data) {

                    var pkps_location = e.originalEvent.detail;

                    console.log("pickups-after-choosen catched event", pkps_location);

                    $("input[name=shipping_ups_pickup_id]").val(pkps_location.iid);

                    $("input[name=shipping_additional_information]").val(JSON.stringify(pkps_location));

                    var html = pkps_location.title + " <strong>(" + pkps_location.iid + ")</strong>" +
                        "<br />" + pkps_location.city + ", " + pkps_location.street + "" +
                        "<br />" + pkps_location.zip;

                    self.pickInfo.html(html).show();
                    self.block.removeClass(self.invalidClass);
                });
            }
        };

    })(jQuery);

    setTimeout(function() {
        window.UPSShip.init();
    }, 3000)

    //]]>
</script>

<!-- design/frontend/base/default/template/checkout/onepage/shipping_method/additional.phtml -->
<?php if (!$this->getQuote()->isVirtual()): ?>
    <?php echo $this->helper('giftmessage/message')->getInline('onepage_checkout', $this->getQuote(), $this->getDontDisplayContainer()) ?>
<?php endif; ?>
